# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
post_install do |installer|
  
  installer.generated_projects.each do |project|
    
    project.targets.each do |target|
      
      target.build_configurations.each do |config|
        
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'

      end
      
    end
    
  end
  
end
target 'TravelPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TravelPro
  pod 'pop'
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'KFGradientProgressView'
  pod 'SwiftMessages'
  pod 'ReachabilitySwift'
  pod 'AppCenter'
  pod 'FSCalendar'
  pod 'AWSS3'
  pod 'AWSCore'
  pod 'WXImageCompress'
  pod 'GoogleSignIn'
  pod 'FirebaseCore'
  pod 'FBSDKLoginKit'
  pod 'SDWebImage'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
  pod 'FirebaseAuth'
  # Mix Panel Tracker
  pod 'Mixpanel-swift'
  
  target 'TravelProTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TravelProUITests' do
    # Pods for testing
    
  end
  
  target 'locationpush' do
      pod 'Mixpanel-swift'
  end
  
end
